### ISSUE TITLE
is this active?

### ISSUE THREAD

**Issue by kurktchiev** [linuxserver/docker-monicahq#5]
is this repo active and being included in the offiical image list? just checking before I start whacking at it :)

**Comment by aptalca** [comment]
It was never published

**Comment by kurktchiev** [comment]
no i see that its not pushed out, I guess the question i am having is: will it be or should I just build off of what you have here for my own deployment?

**Comment by aptalca** [comment]
This was just a draft that was worked on 2-3 years ago. No idea if someone on the team will decide to pick it up again (unlikely). Feel free to fork and update as necessary for your own use but we won't be providing any support ;-)
